### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by Hesoyam** [mgol/npm-bump#11]
This line fails on windows:
https://github.com/mgol/npm-bump/blob/c592c387ff32422e2f41ffe57885d956422a8d5e/lib/cli.js#L44

```
Version bumped from 0.0.1-beta.0 to 0.0.1-beta.1
fatal: pathspec 'C\:\\Users\\username\\path\\to\\folder/package.json' did not match any files
C:\Users\username\path\to\folder\node_modules\npm-bump\bin\npm-bump:22
        throw error;
        ^

Error: Command failed: git add C\:\\Users\\username\\path\\to\\folder/package.json
fatal: pathspec 'C\:\\Users\\username\\path\\to\\folder/package.json' did not match any files

    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at run (C:\Users\username\path\to\folder\node_modules\npm-bump\lib\cli.js:46:32)
    at doBump (C:\Users\username\path\to\folder\node_modules\npm-bump\lib\cli.js:61:13)
    at releaseType (C:\Users\username\path\to\folder\node_modules\npm-bump\lib\cli.js:120:9)
    at Object.<anonymous> (C:\Users\username\path\to\folder\node_modules\npm-bump\bin\npm-bump:17:65)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by mgol** [comment]
Thanks for the report. I think I fixed it, although I have no way of verifying it right now. Report issues and, even better, PRs.

**Comment by andywillis** [comment]
@mgol @Hesoyam This issue is solved with [https://github.com/substack/node-shell-quote/pull/34](https://github.com/substack/node-shell-quote/pull/34) but there hasn't been any activity on the repo in a long while. There are PRs dating back to 2013 still waiting to be merged, and it's unlikely this one will be. In the meantime this module remains for broken for Windows users.

**Comment by mgol** [comment]
@andywillis 

> There are PRs dating back to 2013 still waiting to be merged, and it's unlikely this one will be.

There's no PR open against this repository that fixes Windows-related issues. There are no PRs submitted in 2013 that are still open so I'm not sure what you're talking about. If you submit a PR I can look into it.

**Comment by lautarobock** [comment]
still happen
