### ISSUE TITLE
git commit subcommand fails on Windows 10 (probably due to ' ' instead of " ")

### ISSUE THREAD

**Issue by adamborys** [mgol/npm-bump#15]
Tried in Git Bash, Powershell and cmd
```error: pathspec '1.1.10'' did not match any file(s) known to git
child_process.js:669
throw err;
^
Error: Command failed: git commit -m 'Tag 1.1.10'
error: pathspec '1.1.10'' did not match any file(s) known to git
at checkExecSyncError (child_process.js:629:11)
at execSync (child_process.js:666:13)
at run ((...)\node_modules\npm-bump\lib\cli.js:72:13)
at doBump ((...)\node_modules\npm-bump\lib\cli.js:110:13)
at releaseType ((...)\node_modules\npm-bump\lib\cli.js:213:9)
at (...)\deploy.js:12:52
at Object.<anonymous> ((...)\deploy.js:40:3)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)```

**Comment by mgol** [comment]
Thanks; would you want to submit a PR with the fix?

**Comment by mgol** [comment]
It looks like `shell-quote` doesn't support Windows:
https://github.com/substack/node-shell-quote/issues/38#issuecomment-527465696

**Comment by mgol** [comment]
Although, there was a PR adding Windows support almost 2 years ago:
https://github.com/substack/node-shell-quote/pull/34
I'm not sure what the problem is then.
